# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/toshiba/tostab03/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/toshiba/tostab03/proprietary/bin/glgps_nvidiaTegra2android:/system/bin/glgps_nvidiaTegra2android \
    vendor/toshiba/tostab03/proprietary/bin/bcmgps:/system/bin/bcmgps \
    vendor/toshiba/tostab03/proprietary/etc/asound.conf:/system/etc/asound.conf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_aacdec.axf:/system/etc/firmware/nvmm_aacdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_adtsdec.axf:/system/etc/firmware/nvmm_adtsdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_h264dec.axf:/system/etc/firmware/nvmm_h264dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_jpegdec.axf:/system/etc/firmware/nvmm_jpegdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_jpegenc.axf:/system/etc/firmware/nvmm_jpegenc.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_manager.axf:/system/etc/firmware/nvmm_manager.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_mp3dec.axf:/system/etc/firmware/nvmm_mp3dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_mpeg4dec.axf:/system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_reference.axf:/system/etc/firmware/nvmm_reference.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_service.axf:/system/etc/firmware/nvmm_service.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_sorensondec.axf:/system/etc/firmware/nvmm_sorensondec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_vc1dec.axf:/system/etc/firmware/nvmm_vc1dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_wavdec.axf:/system/etc/firmware/nvmm_wavdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_wmadec.axf:/system/etc/firmware/nvmm_wmadec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_wmaprodec.axf:/system/etc/firmware/nvmm_wmaprodec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvrm_avp.bin:/system/etc/firmware/nvrm_avp.bin \
    vendor/toshiba/tostab03/proprietary/lib/egl/libEGL_perfhud.so:/system/lib/egl/libEGL_perfhud.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libEGL_tegra.so:/system/lib/egl/libEGL_tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv1_CM_perfhud.so:/system/lib/egl/libGLESv1_CM_perfhud.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv1_CM_tegra.so:/system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv2_perfhud.so:/system/lib/egl/libGLESv2_perfhud.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv2_tegra.so:/system/lib/egl/libGLESv2_tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/camera.tegra.so:/system/lib/hw/camera.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/gps.tegra.so:/system/lib/hw/gps.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/gralloc.tegra.so:/system/lib/hw/gralloc.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/hwcomposer.tegra.so:/system/lib/hw/hwcomposer.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/lights.tegra.so:/system/lib/hw/lights.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/sensors.tegra.so:/system/lib/hw/sensors.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/libardrv_dynamic.so:/system/lib/libardrv_dynamic.so \
    vendor/toshiba/tostab03/proprietary/lib/libasound.so:/system/lib/libasound.so \
    vendor/toshiba/tostab03/proprietary/lib/libcgdrv.so:/system/lib/libcgdrv.so \
    vendor/toshiba/tostab03/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
    vendor/toshiba/tostab03/proprietary/lib/libmlplatform.so:/system/lib/libmlplatform.so \
    vendor/toshiba/tostab03/proprietary/lib/libmpl.so:/system/lib/libmpl.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvasfparserhal.so:/system/lib/libnvasfparserhal.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvaviparserhal.so:/system/lib/libnvaviparserhal.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvavp.so:/system/lib/libnvavp.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvcontrol_jni.so:/system/lib/libnvcontrol_jni.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvcpud_client.so:/system/lib/libnvcpud_client.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvcpud.so:/system/lib/libnvcpud.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvddk_2d.so:/system/lib/libnvddk_2d.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvddk_2d_v2.so:/system/lib/libnvddk_2d_v2.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvdispmgr_d.so:/system/lib/libnvdispmgr_d.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_asfparser.so:/system/lib/libnvmm_asfparser.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_audio.so:/system/lib/libnvmm_audio.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_aviparser.so:/system/lib/libnvmm_aviparser.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_camera.so:/system/lib/libnvmm_camera.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_contentpipe.so:/system/lib/libnvmm_contentpipe.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_image.so:/system/lib/libnvmm_image.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite_audio.so:/system/lib/libnvmmlite_audio.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite.so:/system/lib/libnvmmlite.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite_utils.so:/system/lib/libnvmmlite_utils.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite_video.so:/system/lib/libnvmmlite_video.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_manager.so:/system/lib/libnvmm_manager.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_misc.so:/system/lib/libnvmm_misc.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_msaudio.so:/system/lib/libnvmm_msaudio.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_parser.so:/system/lib/libnvmm_parser.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_service.so:/system/lib/libnvmm_service.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm.so:/system/lib/libnvmm.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_utils.so:/system/lib/libnvmm_utils.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_vc1_video.so:/system/lib/libnvmm_vc1_video.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_video.so:/system/lib/libnvmm_video.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_vp6_video.so:/system/lib/libnvmm_vp6_video.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_writer.so:/system/lib/libnvmm_writer.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_dtvtuner.so:/system/lib/libnvodm_dtvtuner.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_hdmi.so:/system/lib/libnvodm_hdmi.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_imager.so:/system/lib/libnvodm_imager.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_misc.so:/system/lib/libnvodm_misc.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_query.so:/system/lib/libnvodm_query.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvomxadaptor.so:/system/lib/libnvomxadaptor.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvomxilclient.so:/system/lib/libnvomxilclient.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvomx.so:/system/lib/libnvomx.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvos.so:/system/lib/libnvos.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvparser.so:/system/lib/libnvparser.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvrm_graphics.so:/system/lib/libnvrm_graphics.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvrm.so:/system/lib/libnvrm.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvsm.so:/system/lib/libnvsm.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvtvmr.so:/system/lib/libnvtvmr.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvwinsys.so:/system/lib/libnvwinsys.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvwsi.so:/system/lib/libnvwsi.so \
    vendor/toshiba/tostab03/proprietary/lib/libstagefrighthw.so:/system/lib/libstagefrighthw.so \
    vendor/toshiba/tostab03/proprietary/lib/omxplayer.so:/system/lib/omxplayer.so \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/alsa.conf:/system/usr/share/alsa/alsa.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/cards/aliases.conf:/system/usr/share/alsa/cards/aliases.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/center_lfe.conf:/system/usr/share/alsa/pcm/center_lfe.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/default.conf:/system/usr/share/alsa/pcm/default.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/dmix.conf:/system/usr/share/alsa/pcm/dmix.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/dpl.conf:/system/usr/share/alsa/pcm/dpl.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/dsnoop.conf:/system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/front.conf:/system/usr/share/alsa/pcm/front.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/iec958.conf:/system/usr/share/alsa/pcm/iec958.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/modem.conf:/system/usr/share/alsa/pcm/modem.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/rear.conf:/system/usr/share/alsa/pcm/rear.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/side.conf:/system/usr/share/alsa/pcm/side.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround40.conf:/system/usr/share/alsa/pcm/surround40.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround41.conf:/system/usr/share/alsa/pcm/surround41.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround50.conf:/system/usr/share/alsa/pcm/surround50.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround51.conf:/system/usr/share/alsa/pcm/surround51.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround71.conf:/system/usr/share/alsa/pcm/surround71.conf \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/bt_vendor.conf:/system/etc/bluetooth/bt_vendor.conf
